# Generated by Django 4.0.5 on 2022-12-10 00:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('productivity_k', models.FloatField()),
                ('fav_temp_bot', models.FloatField(default=django.db.models.expressions.F('fav_temp_top'))),
                ('fav_temp_top', models.FloatField(default=django.db.models.expressions.F('fav_temp_bot'))),
                ('fav_precip_bot', models.FloatField(default=django.db.models.expressions.F('fav_precip_top'))),
                ('fav_precip_top', models.FloatField(default=django.db.models.expressions.F('fav_precip_bot'))),
            ],
            options={
                'db_table': 'cultures',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'periods',
            },
        ),
        migrations.CreateModel(
            name='Soil_quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('fertility_k', models.FloatField()),
            ],
            options={
                'db_table': 'soil_qualities',
            },
        ),
        migrations.CreateModel(
            name='Regression_prognoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_temp', models.FloatField()),
                ('avg_precip', models.FloatField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.period')),
            ],
        ),
        migrations.CreateModel(
            name='Meteo_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.period')),
            ],
            options={
                'db_table': 'meteo_reports',
            },
        ),
        migrations.AddConstraint(
            model_name='culture',
            constraint=models.CheckConstraint(check=models.Q(('fav_temp_bot__lte', django.db.models.expressions.F('fav_temp_top'))), name='fav_temp_bot_top_check_const'),
        ),
        migrations.AddConstraint(
            model_name='culture',
            constraint=models.CheckConstraint(check=models.Q(('fav_precip_bot__lte', django.db.models.expressions.F('fav_precip_top'))), name='fav_precip_bot_top_check_const'),
        ),
    ]
