# Generated by Django 4.0.5 on 2023-01-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meteo_report_weather_meteo_report_wind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regression_prognose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_avg', models.FloatField(null=True)),
                ('prec_avg', models.FloatField(null=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.period')),
            ],
            options={
                'db_table': 'regression_prognoses',
            },
        ),
    ]
